name: Build and test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_test:
    name: Build and test local
    if: github.repository_owner == 'ParadoxGameConverters'
    runs-on: [self-hosted, windows]

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: recursive

    - name: "Build solution"
      run: |
       cd "C:\Program Files\Microsoft Visual Studio\2022\Community\Msbuild\Current\Bin\"
       .\MSBuild.exe -m -p:Configuration=Release $Env:GITHUB_WORKSPACE\tests\CommonItemsTests.sln

    - name: "Run tests"
      run: |
       cd $Env:GITHUB_WORKSPACE\tests\Release
       .\CommonItemsTests.exe

    - name: "Cleanup"
      if: always()
      run: |
        Get-ChildItem -Path $Env:GITHUB_WORKSPACE -Recurse -Force | Remove-Item -force -recurse

  build_test:
    name: Build and test foreign
    if: github.repository_owner != 'ParadoxGameConverters'
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: recursive

    - name: "Build solution"
      run: |
       cd "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Msbuild\Current\Bin\"
       .\MSBuild.exe -m -p:Configuration=Release $Env:GITHUB_WORKSPACE\tests\CommonItemsTests.sln

    - name: "Run tests"
      run: |
       cd $Env:GITHUB_WORKSPACE\tests\Release
       .\CommonItemsTests.exe
